USE [master]
GO


CREATE DATABASE [RestApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RestApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RestApi.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RestApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RestApi_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [RestApi] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RestApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RestApi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RestApi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RestApi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RestApi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RestApi] SET ARITHABORT OFF 
GO
ALTER DATABASE [RestApi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RestApi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RestApi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RestApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RestApi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RestApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RestApi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RestApi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RestApi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RestApi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RestApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RestApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RestApi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RestApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RestApi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RestApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RestApi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RestApi] SET RECOVERY FULL 
GO
ALTER DATABASE [RestApi] SET  MULTI_USER 
GO
ALTER DATABASE [RestApi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RestApi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RestApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RestApi] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
CREATE LOGIN [restApi] WITH PASSWORD=N'restApi', DEFAULT_DATABASE=[RestApi], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [RestApi]
GO
/****** Object:  User [restApi]    Script Date: 14/1/2022 20:00:40 ******/
CREATE USER [restApi] FOR LOGIN [restApi] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [restApi]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 14/1/2022 20:00:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([Id], [Nombre], [Apellido], [Email], [Password]) VALUES (1, N'Daniel', N'Deve', N'deve.daniel@gmail.com', N'P@55w0rd')
GO
INSERT [dbo].[Users] ([Id], [Nombre], [Apellido], [Email], [Password]) VALUES (2, N'Juan', N'Perez', N'juan.perez@gmail.com', N'P3r3z1')
GO
INSERT [dbo].[Users] ([Id], [Nombre], [Apellido], [Email], [Password]) VALUES (3, N'Pablo', N'Lopez', N'pablo.lopez@gmail.com', N'PabloL12')
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
USE [master]
GO
ALTER DATABASE [RestApi] SET  READ_WRITE 
GO
